[build]
  base = "site/"
  command = "yarn export && ../make build"
  functions = "functions"
  publish = "__sapper__/export"
[build.environment]
  GO_IMPORT_PATH = "github.com/pahosler/am4-alliance-api"
