[build]
#  command = "yarn export"
  command = "make build"
  functions = "functions"
  base = "lambda"
#  publish = "__sapper__/export"
[build.environment]
  GO_IMPORT_PATH = "github.com/pahosler/am4-alliance-api"
